<option value="">Select A Treatment</option>
<option value="woodsLamp">Wood's Lamp</option>
<option value="Activyl">Activyl</option>
<option value="activylTickPlus">Activyl Tick Plus</option>
<option value="advantagemulti">Advantage Multi</option>
<option value="bordetellaIn">Bordetella In</option>
<option value="Bravecto">Bravecto</option>
<option value="CanineInfluenza">Canine Influenza</option>
<option value="Capstar">Capstar</option>
<option value="Credelio">Credelio</option>
<option value="DA2PPV">DA2PPV</option>
<option value="DentalCleaning">Dental Cleaning</option>
<option value="Droncit">Droncit</option>
<option value="Drontal">Drontal</option>
<option value="DrontalPlus">DrontalPlus</option>
<option value="FecalFloat">Fecal Float</option>
<option value="FleaBath">Flea Bath</option>
<option value="FVRCP">FVRCP</option>
<option value="FrontlinePlus">Frontline Plus</option>
<option value="FungalBath">Fungal Bath</option>
<option value="GiardiaAntigentest">Giardia Antigen Test</option>
<option value="Heartgard">Heartgard</option>
<option value="HeartwormTest">Heartworm Test</option>
<option value="HistopathologyTest">Histopathology Test</option>
<option value="HW4Dx">HW4Dx+</option>
<option value="IntraTracII">Intra-Trac II+</option>
<option value="Iverhart">Iverhart</option>
<option value="Ivermax">Ivermax</option>
<option value="Ivermectin">Ivermectin</option>
<option value="Labwork">Labwork</option>
<option value="Lepto">Lepto 4</option>
<option value="Revolution">Revolution</option>
<option value="ReWeigh">Re-Weigh</option>
<option value="Pyrantel">Pyrantel</option>
<option value="Panacur">Panacur</option>